name = 'Swan Saga'

modules = [
   '@rpgjs/title-screen',
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[titleScreen]
    title = 'Swan Saga'

[start]
    map = 'simplemap'
    graphic = 'female'
    hitbox = [16, 16]

